//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingCollection
    {
        public int ParkingCollectionId { get; set; }
        public Nullable<int> ParkingAddressId { get; set; }
        public System.DateTime ParkingDate { get; set; }
        public string VechileRegNo { get; set; }
        public Nullable<int> VechileTypeId { get; set; }
        public System.DateTime InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ParkingAddress ParkingAddress { get; set; }
        public virtual ParkingDetail ParkingDetail { get; set; }
    }
}
