//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingDetail()
        {
            this.ParkingCollections = new HashSet<ParkingCollection>();
        }
    
        public int ParkingdetailId { get; set; }
        public Nullable<int> ParkingAddressId { get; set; }
        public Nullable<int> VechileTypeId { get; set; }
        public int MaxSlot { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ParkingAddress ParkingAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingCollection> ParkingCollections { get; set; }
        public virtual VechileType VechileType { get; set; }
    }
}
