//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserParkingAddress
    {
        public int UserParkingAddressId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParkingAddressId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ParkingAddress ParkingAddress { get; set; }
        public virtual User User { get; set; }
    }
}
